### ISSUE TITLE
[Discussion] What's a reason to run tests here

### ISSUE THREAD

**Issue by menshikh-iv** [conda-forge/gensim-feedstock#10]
Current repository used tarball from PyPI for building conda-wheels, if gensim tarball on PyPI, this means, that all code already tested.

For this reason, my question: **Should we run all tests here or this has no sense?**  @tmylk @souravsingh

Also, I have no understanding, what exactly happens here (I mean - we build binary packages for coda or what)?

CC: @piskvorky

**Comment by isuruf** [comment]
What happens is that binary packages are built and uploaded to anaconda.org.

>  Should we run all tests here or this has no sense? 

We prefer running all tests especially packages with compiled extensions to make sure the built binary package works.

**Comment by menshikh-iv** [comment]
aha, thanks @isuruf!
