### ISSUE TITLE
Incorrect licence

### ISSUE THREAD

**Issue by piskvorky** [conda-forge/gensim-feedstock#29]
I'm not familiar with the Conda process, but its Gensim page https://anaconda.org/conda-forge/gensim lists an incorrect licence, LGPL-3.0:

<img width="1440" alt="Screen Shot 2019-05-01 at 12 38 48" src="https://user-images.githubusercontent.com/610412/57013955-3077a480-6c0e-11e9-8727-1c9209e5acb2.png">

Gensim's actual licence is LGPL-2.1.

**Comment by menshikh-iv** [comment]
@piskvorky you can change this here: https://github.com/conda-forge/gensim-feedstock/blob/6820da579858cebbcb25edebe38567bb65fb21b3/recipe/meta.yaml#L65-L68

**Comment by piskvorky** [comment]
I can't no access to this repo.

**Comment by menshikh-iv** [comment]
@piskvorky check readme: https://github.com/conda-forge/gensim-feedstock/blob/master/README.md#updating-gensim-feedstock 

> If you would like to improve the gensim recipe or build a new package version, please fork this repository and submit a PR

making changes directly in the current repo isn't recommended by conda

**Comment by piskvorky** [comment]
Thanks @menshikh-iv , I'll open a PR with the licence fix.

@mpenkov we'll have to decide what to do about Conda. I'm uncomfortable providing support for a platform we have no control over, doing free labour for a commercial for-profit VC-backed entity Anaconda Inc, which we don't use (and who doesn't pay us anything for such support and PR).

**Comment by mpenkov** [comment]
@piskvorky I can see where you're coming from. Personally, I don't use conda at all, so I have little personal interest in maintaining the feedstock.

On the other hand, these things are relatively labor non-intensive and benefit a significant number of people. They also expand our user base, so there is some benefit there.
