### ISSUE TITLE
Incorrect numpy version forces gensim to be installed from the defaults channel

### ISSUE THREAD

**Issue by setu4993** [conda-forge/gensim-feedstock#33]
[This line](https://github.com/conda-forge/gensim-feedstock/blob/74891700224bf2d8523a04ad46b96a9fd598956c/recipe/meta.yaml#L25) should be:
`numpy >= 1.11.3`

Reference on the gensim website [dependencies list](https://radimrehurek.com/gensim/install.html):
- Python >= 2.7 (tested with versions 2.7, 3.5 and 3.6)
- NumPy >= 1.11.3
- SciPy >= 0.18.1
- Six >= 1.5.0
- smart_open >= 1.2.1

**Comment by mpenkov** [comment]
Thanks! Are you able to make a PR?

**Comment by setu4993** [comment]
@mpenkov: Just created https://github.com/conda-forge/gensim-feedstock/pull/34 as a fix.
