### ISSUE TITLE
Question about CI

### ISSUE THREAD

**Issue by souravsingh** [conda-forge/gensim-feedstock#5]
@ocefpaf I have a question about the CI for feedstock, Do the recipe maintainers have access to run the CI tests for their feedstock and can they restart the CI anytime, in case it fails?

**Comment by ocefpaf** [comment]
Yep. They do :smile:

**Comment by menshikh-iv** [comment]
Unfortunately, I have no permissions for this actions @ocefpaf 


No buttons in Appveyor
![image](https://user-images.githubusercontent.com/15094669/30968519-0c59b150-a479-11e7-86ee-c4133c10be64.png)

Unactive button in CircleCI
![image](https://user-images.githubusercontent.com/15094669/30968563-29ecfa4c-a479-11e7-9c28-53f63a7a9fc3.png)

**Comment by menshikh-iv** [comment]
ping @ocefpaf

**Comment by isuruf** [comment]
@menshikh-iv, are you still lacking permissions?

**Comment by menshikh-iv** [comment]
@isuruf unfortunately yes.

**Comment by isuruf** [comment]
@menshikh-iv, which CI service? For appveyor you need to logout and select `conda-forge` as the team

**Comment by menshikh-iv** [comment]
Aha, thanks for info @isuruf!
